[TB] Standalone testbench for the cluster and minor `RTL` fix.
pulp-platform/pulp_cluster pull request #34
Opened 2023-03-24 14:03 UTC by luca-valente

* Self-checking capabilities, aligned with `exit(status)` from
   runtime
 * Emulate 512kB of L2 
* Proper parametrization of the CDC interface
 * Drive `aw_top` to 0

2023-03-27 08:40 UTC, OttG commented
LGTM, @micprog anything to add? Otherwise I merge

2023-03-27 09:01 UTC, micprog requested changes
I haven't tested it myself, in general, it looks OK to get the standalone mode running, but the added files conflict with the PULP main files. I suggest adapting all (or most) of the required include files to parameters or using a similar method of including the files as is now present in pulp (basically bypassing bender for this include directory). Bypassing is a very ugly solution, so I would prefer changing everything to parameters.

2023-03-27 09:34 UTC, luca-valente commented on Bender.yml
> +
Definetely!

2023-03-27 09:34 UTC, luca-valente commented on Bender.yml
> +  - include/pulp_interfaces.sv
It makes perfect sense :smile:

2023-03-30 09:03 UTC, micprog commented
LGTM, feel free to merge 👍

2023-03-31 09:53 UTC, merged