Integrate TCDM scrubber (ECC manager).
pulp-platform/pulp_cluster pull request #54
Opened 2024-02-26 19:08 UTC by yvantor

2024-02-27 18:56 UTC, yvantor commented
I have opened two PRs also in the [runtime](https://github.com/pulp-platform/pulp-runtime/pull/43) and [regression tests](https://github.com/pulp-platform/regression_tests/pull/11).
I define this PR as ready because I think it makes sense if you guys already have a look at it, but before merging I will add the ECC regression to CI and merge the two PRs in runtime and regression tests.
Cheers!

2024-02-28 08:46 UTC, ricted98 commented
LGTM. I was able to build the design and run the test out of the box. As a plus, I could rebase my branch with the fault injection scripts on top of this branch to perform fault injection in the memory and test the behavior of the scrubber.

2024-02-28 08:57 UTC, ricted98 commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_TCDM_SCRUBBER_ID = 9;  // 0x2400 - 0x2800
Are we sure that we are not breaking some compatibility by reassigning this ID to the scrubber instead of appending it at the end?

2024-02-28 08:59 UTC, yvantor commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_TCDM_SCRUBBER_ID = 9;  // 0x2400 - 0x2800
It should be fine because the runtime is not using any of the last two slave devices (not even sure why they are there honestly, I never investigated in detail). Maybe @micprog has hints

2024-02-28 09:16 UTC, ricted98 commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_TCDM_SCRUBBER_ID = 9;  // 0x2400 - 0x2800
Clear. I was looking better [at the code](https://github.com/pulp-platform/pulp_cluster/blob/71a92abcda6ecf547320a32b0c65313a220eb53c/rtl/pulp_cluster.sv#L734) and apparently it is expected that Error and Ext are mapped to the two highest IDs. The current change should be correct.

2024-02-28 09:22 UTC, ricted98 commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_TCDM_SCRUBBER_ID = 9;  // 0x2400 - 0x2800
I was looking at the code. There might be some positional assumptions on the EXT periph.
[Here](https://github.com/pulp-platform/pulp_cluster/blob/71a92abcda6ecf547320a32b0c65313a220eb53c/rtl/pulp_cluster.sv#L585) the SPER_EXT_ID is used, but [here](https://github.com/pulp-platform/pulp_cluster/blob/71a92abcda6ecf547320a32b0c65313a220eb53c/rtl/pulp_cluster.sv#L734) the assumption is that peripherals are mapped from `0` to `Cfg.NumSlvPeriphs-2`. The current change should be already compliant if I am not mistaken.

2024-02-28 11:45 UTC, ricted98 commented on rtl/tcdm_banks_wrap.sv
>                      scrub_fix, scrub_uncorrectable;
These signals seem to be no longer needed. Could be worth removing them?

2024-02-28 14:03 UTC, yvantor commented on rtl/tcdm_banks_wrap.sv
>                      scrub_fix, scrub_uncorrectable;
Correct

2024-02-28 14:08 UTC, yvantor commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_TCDM_SCRUBBER_ID = 9;  // 0x2400 - 0x2800
This makes the approach more logic I think. In the current way we are still mapping the all the slave peripheral buses into the `Cfg.NumSlvPeriphs-2` scope. If we added the scrubber ID at the end, that bus indexing should have changed as well. Do you also agree?

2024-02-28 14:13 UTC, ricted98 commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_TCDM_SCRUBBER_ID = 9;  // 0x2400 - 0x2800
Yes, I agree. I think the current version is fine with respect to my original doubt.

2024-02-28 14:45 UTC, micprog requested changes

2024-02-28 14:45 UTC, micprog commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_EXT_ID           = 10; // 0x2800 - 0x2C00
It may make sense to use `SPER_EXT_ID`. AFAIK @FrancescoConti has some insight on how this was used previously, but if I remember from him this is left to be used for other peripherals if needed. Just a comment, no need to act on this though.

2024-02-28 14:45 UTC, micprog commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned NB_SPERIPHS = 11;
This is probably not related to this PR, but why do we have multiple separate definitions of these values? AFAIK these are defines, parameters here, and parameters in the pulp top-level, leading to very likely mismatch. I think we should attempt to unify these. Not necessary for this PR, but something to be aware of.

2024-02-28 14:45 UTC, micprog commented on rtl/tcdm_banks_wrap.sv
> +        .test_write_mask_ni    ( test_write_mask_ni[i]   )
Unless you intend on using this, I recommend leaving the test_write_mask disconnected. It is there to manipulate the data written to the SRAM to inject faults. Best to also disable the parameter of the module, as you should then be able to use banks in the backend that have simpler or no bitmasks, and FPGAs should work better as they generally only support byte masks, not individual bits.

2024-02-28 14:45 UTC, micprog commented on rtl/tcdm_banks_wrap.sv
> -    assign tcdm_slave[i].gnt    =  1'b1;
You may have lost the gnt signal, this is likely still needed in the ECC disabled case...

2024-02-28 14:45 UTC, micprog commented on rtl/tcdm_banks_wrap.sv
> +        .test_write_mask_ni    ( test_write_mask_ni[i]   )
We should probably also update the ECC manager to support deactivating these registers and removing them from synthesis.

2024-02-28 14:59 UTC, yvantor commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned NB_SPERIPHS = 11;
On this I agree 100%, my idea was to use only the parameters defined in the package, but then I forgot to adapt the code when working on the parameters cleanup. On the other hand, I think it makes sense to open a dedicate PR because this could be merged also in the master branch. What do you think?

2024-02-28 15:00 UTC, yvantor commented on rtl/tcdm_banks_wrap.sv
> -    assign tcdm_slave[i].gnt    =  1'b1;
Ah yes... I removed a bunch of signals ad this one was a victim xD

2024-02-28 15:01 UTC, yvantor commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_EXT_ID           = 10; // 0x2800 - 0x2C00
Sure, I will ask Francesco as well

2024-02-28 15:32 UTC, yvantor commented on rtl/tcdm_banks_wrap.sv
> -    assign tcdm_slave[i].gnt    =  1'b1;
Should be fixed!

2024-02-28 16:13 UTC, FrancescoConti commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_EXT_ID           = 10; // 0x2800 - 0x2C00
The `SPER_EXT_ID` must be kept as it corresponds to the `per2axi` port. The comment for that and `SPER_ERROR_ID` are a bit misleading as actually both direct accesses to `SPER_EXT_ID` and `SPER_ERROR_ID` will be redirected to errors. However, both parameters need to be kept as `SPER_EXT_ID` is used to index the correct interface in the `pulp_cluster` top.

2024-02-28 16:13 UTC, FrancescoConti commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_EXT_ID           = 10; // 0x2800 - 0x2C00
Personally, I would change the comment so that the fact that these address spaces are actually unmapped is explicit!

2024-02-28 16:26 UTC, yvantor commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_EXT_ID           = 10; // 0x2800 - 0x2C00
Do you mean the comment on the address space occupied by the two IDs?

2024-02-28 16:42 UTC, FrancescoConti commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_EXT_ID           = 10; // 0x2800 - 0x2C00
yes

2024-02-28 16:43 UTC, FrancescoConti commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned NB_SPERIPHS = 11;
👍

2024-02-28 20:40 UTC, yvantor commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned SPER_EXT_ID           = 10; // 0x2800 - 0x2C00
I have changed the [comments](https://github.com/pulp-platform/pulp_cluster/blob/yt/scrubber/packages/pulp_cluster_package.sv#L146-L147) to clarify that those two IDs have correspondence to the cluster memory mapped.
If you all agree that no hardware changes must be made to integrate this new peripheral, I think we can resolve the conversation!

2024-02-29 10:30 UTC, yvantor commented
@micprog I should have addressed all the changes you requested, do you think the comments could be resolved?

2024-02-29 12:45 UTC, micprog commented on packages/pulp_cluster_package.sv
> +  parameter int unsigned NB_SPERIPHS = 11;
dedicated PR makes sense to also separate concerns! Just thought I'd already note it here.

2024-02-29 12:49 UTC, micprog approved these changes
LGTM :+1:

2024-02-29 17:19 UTC, yvantor commented
Closing.

2024-02-29 17:19 UTC, merged