Added softmax accelerator
pulp-platform/pulp_cluster pull request #66
Opened 2024-05-07 09:29 UTC by belanoa

2024-05-07 14:07 UTC, yvantor reviewed
There is no regression test added for the accelerator. I think this is required before merging (once we have it, we can also add it to the CI)

2024-05-07 14:07 UTC, yvantor commented on Bender.yml
> +  softex:                 { git: "https://github.com/belanoa/softex.git"       , rev: 9da2870 }
Is this the master branch? Could you please add as a comment the name of the branch it comes from?

2024-05-07 20:48 UTC, FrancescoConti requested changes
The change I request is only the open sourcing of course ;)

2024-05-07 20:48 UTC, FrancescoConti commented on Bender.yml
> +  softex:                 { git: "https://github.com/belanoa/softex.git"       , rev: 9da2870 } # branch: master
Before merging it's better to wait for this to be public (and possibly in the pulp namespace), do you agree @yvantor ?

2024-05-31 15:11 UTC, closed without merging

2024-05-31 15:11 UTC, yvantor commented
Closing as tackeld in #71.