Port astral features to master branch
pulp-platform/pulp_cluster pull request #87
Opened 2024-11-13 17:01 UTC by belanoa

2024-11-13 17:03 UTC, FrancescoConti commented
Great! Are the Chimera guys @arpansur @sermazz @Lore0599 aware of this PR?

2024-12-04 13:38 UTC, alex96295 commented
General comment for the CI:

* It seems that the main common issue across the tests that you have is:

```
fatal: could not get a repository handle for submodule 'pulp-runtime'
```

* There is only one test for which you can get past the error above, i.e. `ParMatrixMul32`. So maybe this hints at some conflicts between the runs. Try to replace this line: https://iis-git.ee.ethz.ch/pulp-restricted/pulp-cluster-nonfree/-/blob/astral/ci.yml?ref_type=heads#L2 with `normal` instead of `recursive`

* Even if the test `ParMatrixMul32` starts correctly, note that it is functionally broken as it raise  illegal instructions, so this is a real bug that needs to be fixed also locally -> https://iis-git.ee.ethz.ch/github-mirror/pulp_cluster/-/jobs/1499281

2024-12-19 16:43 UTC, alex96295 commented
I gave a first pass and left some comments

I suggest we:

* Write a detailed section in the CHANGELOG to highlight what was added and fixed; for a release, we should ideally wait for all the dependencies to point to a release (stable version) instead of a branch, but we can release an alpha version
* Improve the README with a `Dependencies` section. In the future, we could use online docs like in other repos (e.g. snitch cluster etc)

2024-12-19 17:55 UTC, FrancescoConti requested changes
Hi all, I left a few comments. Some of these are cleanup and could be postponed to another PR, but given the already pretty massive size of this one I think it makes more sense to do the job cleanly already here.

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/cluster_peripherals.sv
> +`include "common_cells/registers.svh"
Are registers from `registers.svh` used anywhere in this file? it does not seem so to me...
If so, well, I am not a big fan 😆

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/cluster_peripherals.sv
> +  `REG_BUS_TYPEDEF_ALL(icache, logic[31:0], logic[31:0], logic[3:0])
similarly to what recommended for my own macro dark magic in `hci_helpers.svh`, I'd recommend adding a comment here pointing directly to https://github.com/pulp-platform/register_interface/blob/master/include/register_interface/typedef.svh#L34 for explanation of what this does.

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/cluster_peripherals.sv
> +`ifdef SNITCH_ICACHE
do we have to keep this controlled by a define? Can't we make this parametric?

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/core_region.sv
> +  // localparam N_EXT_PERF_COUNTERS_ACTUAL = 5;
I'd just remove this commented out line

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/hwpe_subsystem.sv
> +import pulp_cluster_package::*;
move imports inside module

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/hwpe_subsystem.sv
> +  localparam hci_package::hci_size_parameter_t `HCI_SIZE_PARAM(tcdm_softex) = '{
add comment referring explicitly to https://github.com/pulp-platform/hci/blob/master/rtl/common/hci_helpers.svh for these macros...

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/pulp_cluster.sv
> +// FIXME: iDMA
remove dead code...

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/pulp_cluster.sv
> +// FIXME: iDMA
remove dead code... unless you know what this FIXME actually means

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/pulp_cluster.sv
> +`ifdef TARGET_MCHAN
can we make this a parameter instead of this define?

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/pulp_cluster.sv
> +`ifdef SNITCH_ICACHE
can we make this a parameter?

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/pulp_cluster.sv
> +`ifdef SNITCH_ICACHE
also: what is the default? are we sure that the Snitch I$ is faster/more efficient/... than the shared I$?

2024-12-19 17:55 UTC, FrancescoConti commented on rtl/tcdm_banks_wrap.sv
> +        .`HCI_SIZE_PARAM(tcdm_target) ( HCI_MEM_SIZE ),
same commeent as above on `hci_helpers.svh`.

2024-12-19 17:56 UTC, FrancescoConti commented
Also, @DanielKellerM @arpansur @sermazz as we discussed already please keep track of this PR

2025-01-04 09:10 UTC, yvantor reviewed
I have requested a few changes, but overall great job! Sorry for getting here so late :)

2025-01-04 09:10 UTC, yvantor commented on rtl/pulp_cluster.sv
> +                                                       // in the cluster control unit.
Put this in line.

2025-01-04 09:10 UTC, yvantor commented on rtl/xbar_pe_wrap.sv
> +  parameter ADDREXT         = 1'b0,
```suggestion
  parameter int unsigned NB_CORES           = 12,
  parameter int unsigned NB_MPERIPHS        = 1,
  parameter int unsigned NB_SPERIPHS        = 10,   
  parameter int unsigned ADDR_WIDTH         = 32,
  parameter int unsigned DATA_WIDTH         = 32,
  parameter int unsigned BE_WIDTH           = 0,
  parameter int unsigned PE_ROUTING_LSB     = 10,
  parameter int unsigned PE_ROUTING_MSB     = 13,
  parameter bit HWPE_PRESENT   = 1'b1,
  parameter bit CLUSTER_ALIAS      = 1,
  parameter logic [11:0] CLUSTER_ALIAS_BASE =  'h000,
  parameter bit ADDREXT         = 1'b0,
```

2025-01-04 09:10 UTC, yvantor commented on rtl/xbar_pe_wrap.sv
> +    assign cluster_alias = 1'b0;
```suggestion
  assign cluster_alias = CLUSTER_ALIAS;
```

2025-01-04 09:10 UTC, yvantor commented on wave.do
Do we need this file? I think having a script for automatically loading the interesting waves makes sense but this is uselessly large. Have a look at how I did it in [RedMulE](https://github.com/pulp-platform/redmule/blob/main/target/sim/vsim/wave.tcl), it should simplify the waves script also for future changes.

2025-02-11 13:20 UTC, sermazz commented on tb/pulp_cluster_tb.sv
> +    HMRPresent: 1,
Small typo: `HMRPresent` parameter is assigned two times

2025-02-24 18:07 UTC, FrancescoConti commented on Bender.yml
This list of authors is totally meaningless now...

2025-02-24 18:20 UTC, FrancescoConti approved these changes

2025-02-24 18:20 UTC, FrancescoConti commented on Bender.yml
> +  - target: mchan
The proliferation of targets with potentially misleading names is a bit dangerous. I think this is safe, but maybe `pulp_cluster_mchan` would be a better name.

2025-02-24 18:20 UTC, FrancescoConti commented on Makefile
> +ETH_HOST = $(shell echo $(HOSTNAME) | grep -q "\.ee\.ethz\.ch$$" && echo 1 || echo 0)
The "standard" way to do this is
```
ifneq (,$(wildcard /etc/iis.version))
	QUESTA ?= questa-2023.4-zr
else
	QUESTA ?=
endif
```

2025-02-24 18:23 UTC, FrancescoConti commented
@belanoa time to bring this one home! 😎

2025-02-24 18:33 UTC, merged